### ISSUE TITLE
This plugin need a version tag

### ISSUE THREAD

**Issue by gitbenb** [chrismou/phergie-irc-plugin-react-weather#1]
currently unable to use composer.json like this with this plugin

 {
    "minimum-stability": "dev",
    "require": {
        "phergie/phergie-irc-bot-react":  "~1",
        "phergie/phergie-irc-plugin-react-pong": "~1",
        "phergie/phergie-irc-plugin-react-feedticker": "~1",
        "phergie/phergie-irc-plugin-react-commandhelp": "~1",
        "chrismou/phergie-irc-plugin-react-google": "~1",
        "chrismou/phergie-irc-plugin-react-audioscrobbler": "~1",
        "phergie/phergie-irc-plugin-react-nickserv": "~1",
        "phergie/phergie-irc-plugin-react-quit": "~1",
        "phergie/phergie-irc-plugin-react-thefuckingweather": "~1",
        "chrismou/phergie-irc-plugin-react-weather": "~1",
        "phergie/phergie-irc-plugin-react-youtube": "~1",
        "phergie/phergie-irc-plugin-react-autojoin": "~1",
        "phergie/phergie-irc-plugin-react-twitter": "~1",
        "phergie/phergie-irc-plugin-react-joinpart": "~1"
    }
}

output this : 
Problem 1
    - The requested package chrismou/phergie-irc-plugin-react-google could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package chrismou/phergie-irc-plugin-react-audioscrobbler could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package chrismou/phergie-irc-plugin-react-weather could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package phergie/phergie-irc-plugin-react-twitter could not be found in any version, there may be a typo in the package name.

**Comment by chrismou** [comment]
Hi

See https://github.com/chrismou/phergie-irc-plugin-react-google/issues/1#issuecomment-68939346 for more details
